kind: pipeline
type: exec
name: default

platform:
  os: windows

steps:
- name: compile
  commands:
    - c:\nuget\nuget.exe restore FormattedTextTest.sln
    - Invoke-MsBuild -Path FormattedTextTest.sln -ShowBuildOutputInCurrentWindow -PassThru

