kind: pipeline
type: exec
name: default

platform:
  os: windows

steps:
- name: restore nuget packages
  commands:
    - c:\nuget\nuget.exe restore FormattedTextTest.sln
- name: build
  commands:
    - Invoke-MsBuild -Path FormattedTextTest.sln -ShowBuildOutputInCurrentWindow -PassThru
- name: create compressed package
  commands:
    - Compress-Archive -Path FormattedTextTestClient\bin\debug\*.* -DestinationPath FormattedTextTest.zip
- name: upload artifacts
  environment:
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
  commands:
    - Write-S3Object -AccessKey $env:access_key -SecretKey $env:secret_key -BucketName FormattedTextTest -File FormattedTextTest.zip -EndpointUrl https://s3.decryptology.net/artifacts

